# Generated by Django 4.2.7 on 2026-01-11 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('Bed', 'Bed'), ('Table', 'Table'), ('Chair', 'Chair'), ('Cupboard', 'Cupboard'), ('Fan', 'Fan'), ('Light', 'Light'), ('Other', 'Other')], max_length=50)),
                ('total_quantity', models.IntegerField(default=1)),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged')], default='Good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
