# Generated by Django 4.2.7 on 2026-01-18 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Bed', 'Bed'), ('Table', 'Table'), ('Chair', 'Chair'), ('Cupboard', 'Cupboard'), ('Fan', 'Fan'), ('Light', 'Light'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Not Fixed', 'Not Fixed'), ('Fixed', 'Fixed'), ('Replaced', 'Replaced')], default='Not Fixed', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Damage Report',
                'verbose_name_plural': 'Damage Reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
