# Generated by Django 4.2.7 on 2026-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Warden', 'Warden'), ('Sub-Warden', 'Sub-Warden'), ('Inventory Staff', 'Inventory Staff')], default='Pending', max_length=50),
        ),
    ]
